export { HomeSection } from "./home-section"
export { AboutSection } from "./about-section"
export { ProjectsSection } from "./projects-section"
export { SkillsSection } from "./skills-section"
export { ExperienceSection } from "./experience-section"
export { ServicesSection } from "./services-section"
export { ContactSection } from "./contact-section"
